# Generated by Django 4.0.6 on 2022-07-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='isBooked',
        ),
    ]
