# Generated by Django 4.0.6 on 2022-07-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_alter_room_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientEmail', models.EmailField(max_length=100)),
                ('clientName', models.CharField(max_length=100)),
                ('clientSurname', models.CharField(max_length=100)),
                ('bookedFrom', models.DateField(auto_now_add=True)),
                ('bookedTo', models.DateField(auto_now_add=True)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
