# Generated by Django 4.0.6 on 2022-07-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='bookedFrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='bookedTo',
            field=models.DateField(),
        ),
    ]
