# Generated by Django 4.0.6 on 2022-07-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_room', '0002_alter_bookingroom_bookedfrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='checkIn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='clientPassportCopy',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
